import { 
  DesireOption, 
  ArchetypeProfile, 
  SevenDayStep,
  AbundancePillar,
  RealityEngineNode,
  LarpMission
} from '../types';

// Цены вынесены в отдельный модуль pricing.ts (единый источник правды для клиента).
export { PRICING_EXPERIMENTS } from './pricing';

export const DESIRE_OPTIONS: DesireOption[] = [
  {
    id: 'money',
    title: 'ДЕНЬГИ & ИЗОБИЛИЕ',
    tagline: '«Позволь себе хотеть больше»',
    hookSubtitle: 'Снять внутренний потолок, перестать демпинговать и открыть поток ресурсов',
    iconName: 'Coins',
    accentColor: 'from-amber-500 to-yellow-300',
    targetHz: 639,
    starterProtocolId: 'proto-money',
    quickAffirmation: 'Ресурсы циркулируют свободно. Я легко принимаю и создаю ценность.',
  },
  {
    id: 'love',
    title: 'ЛЮБОВЬ & МАГНЕТИЗМ',
    tagline: '«Позволь себе быть выбранным»',
    hookSubtitle: 'Убрать страх отвержения, перестать заслуживать любовь и войти в магнетизм',
    iconName: 'Heart',
    accentColor: 'from-rose-500 to-pink-400',
    targetHz: 528,
    starterProtocolId: 'proto-love',
    quickAffirmation: 'Я заслуживаю искренней близости и глубокой связи просто по праву рождения.',
  },
  {
    id: 'confidence',
    title: 'УВЕРЕННОСТЬ & СИЛА',
    tagline: '«Перестань уменьшать себя»',
    hookSubtitle: 'Говорить твердо, держать осанку и перестать извиняться за свое существование',
    iconName: 'Shield',
    accentColor: 'from-purple-500 to-indigo-400',
    targetHz: 741,
    starterProtocolId: 'proto-highagency',
    quickAffirmation: 'Мой голос имеет значение. Я занимаю свое пространство с достоинством.',
  },
  {
    id: 'luck',
    title: 'УДАЧА & СИНХРОНИЧНОСТЬ',
    tagline: '«Начни замечать возможности»',
    hookSubtitle: 'Выйти из режима выживания в режим, где нужные люди и шансы появляются вовремя',
    iconName: 'Sparkles',
    accentColor: 'from-emerald-400 to-teal-300',
    targetHz: 888,
    starterProtocolId: 'proto-opportunity',
    quickAffirmation: 'Мир полон скрытых дверей. Я нахожусь в правильном месте в правильный момент.',
  },
  {
    id: 'energy',
    title: 'ЭНЕРГИЯ & ЖИЗНЬ',
    tagline: '«Верни вкус к жизни»',
    hookSubtitle: 'Сбросить апатию, дофаминовое выгорание и просыпаться с горящими глазами',
    iconName: 'Zap',
    accentColor: 'from-amber-400 to-orange-500',
    targetHz: 432,
    starterProtocolId: 'proto-reset',
    quickAffirmation: 'Мое тело наполнено чистой жизненной силой и вдохновением.',
  },
  {
    id: 'peace',
    title: 'СПОКОЙСТВИЕ & ТИШИНА',
    tagline: '«Отпусти фоновый шум»',
    hookSubtitle: 'Остановить бесконечный диалог в голове, тревожность и перегруз новостями',
    iconName: 'Compass',
    accentColor: 'from-cyan-400 to-blue-500',
    targetHz: 520,
    starterProtocolId: 'proto-deepwork',
    quickAffirmation: 'Внутри меня непоколебимый центр тишины и ясности.',
  },
  {
    id: 'new_life',
    title: 'НОВАЯ ЖИЗНЬ',
    tagline: '«Сделай первый шаг»',
    hookSubtitle: 'Закрыть старую главу, сменить окружение и смело войти в новую версию себя',
    iconName: 'Flame',
    accentColor: 'from-violet-500 to-fuchsia-400',
    targetHz: 963,
    starterProtocolId: 'proto-quantum',
    quickAffirmation: 'Я автор своей следующей главы. Прошлое больше не определяет меня.',
  },
  {
    id: 'everything',
    title: 'ИЗМЕНИТЬ ВСЁ',
    tagline: '«Полный перезапуск реальности»',
    hookSubtitle: 'Комплексный квантовый скачок: деньги, отношения, тело и масштаб проявления',
    iconName: 'Crown',
    accentColor: 'from-purple-500 via-pink-500 to-amber-400',
    targetHz: 963,
    starterProtocolId: 'proto-quantum',
    quickAffirmation: 'Я полностью открываюсь своему высшему потенциалу и безграничному изобилию.',
  },
];

export const ARCHETYPE_PROFILES: Record<string, ArchetypeProfile> = {
  THE_SEEKER: {
    id: 'THE_SEEKER',
    nameRu: 'ИСКАТЕЛЬ ПОТЕНЦИАЛА',
    nameEn: 'THE SEEKER',
    eraTitle: 'Seeking Era → Creation Era',
    tagline: '«Ты чувствуешь, что способен на гораздо большее, но ждешь идеального момента»',
    psychologicalMirror: 
      'Ты постоянно изучаешь новые темы, покупаешь курсы, смотришь подкасты и чувствуешь огромный нераскрытый огонь внутри. Ты видишь чужие успехи и точно знаешь: ты мог бы сделать не хуже, а лучше. Но между «я хочу» и «я сделал» каждый раз вырастает стена из сомнений, перфекционизма и ощущения "я еще не готов". Ты копишь знания, вместо того чтобы монетизировать и проявлять их.',
    rootBlock: 'Иллюзия нехватки компетенций (Скрытый синдром самозванца)',
    metrics: {
      desire: 92,
      action: 41,
      selfBelief: 53,
      receiving: 39,
    },
    firstShiftAdvice: 'Сегодня тебе не нужно читать еще одну книгу. Тебе нужно сделать одно кривое, неидеальное действие в реальном мире, пока мозг не успел включить критика.',
    firstStepAction: 'Отправь 1 сообщение / черновик / предложение, которое откладываешь больше 3 дней, без перепроверки.',
    recommendedHz: 639,
    recommendedProtocolId: 'proto-decision',
    sevenDayJourneyTheme: 'От вечной подготовки к хладнокровному действию',
    shareableQuote: '«Apparently I am entering my creation era. No more overthinking.»',
  },
  THE_BLOCKED_CREATOR: {
    id: 'THE_BLOCKED_CREATOR',
    nameRu: 'ЗАБЛОКИРОВАННЫЙ СОЗДАТЕЛЬ',
    nameEn: 'THE BLOCKED CREATOR',
    eraTitle: 'Doubt Era → Unstoppable Era',
    tagline: '«Огромный талант, скованный страхом критики и отвержения»',
    psychologicalMirror: 
      'У тебя в голове десятки сильных идей, проектов и форматов, но ты держишь их при себе. Когда приходит время показать результат миру или назвать свою настоящую цену, горло перехватывает, а в теле появляется зажим. Ты подсознательно защищаешь себя от возможного осуждения, выбирая оставаться незаметным, хотя внутри задыхаешься от тесноты своего текущего уровня.',
    rootBlock: 'Страх быть увиденным и оцененным (Блок видимости)',
    metrics: {
      desire: 88,
      action: 36,
      selfBelief: 45,
      receiving: 31,
    },
    firstShiftAdvice: 'Твой страх оценки исчезает в ту секунду, когда ты смещаешь фокус с «как я выгляжу» на «какую ценность я несу людям».',
    firstStepAction: 'Опубликуй свою мысль, покажи работу или озвучь свое мнение вслух без попытки всем понравиться.',
    recommendedHz: 741,
    recommendedProtocolId: 'proto-highagency',
    sevenDayJourneyTheme: 'Проявление без стыда и страха критики',
    shareableQuote: '«Exiting my quiet era. Entering my visible abundance era.»',
  },
  THE_RECEIVER: {
    id: 'THE_RECEIVER',
    nameRu: 'ОТДАЮЩИЙ АЛЬТРУИСТ',
    nameEn: 'THE RECEIVER',
    eraTitle: 'Overgiving Era → Receiving Era',
    tagline: '«Ты легко помогаешь и отдаешь другим, но блокируешь поток к себе»',
    psychologicalMirror: 
      'Ты щедрый, эмпатичный и внимательный человек. Ты первый придешь на помощь другу, сделаешь скидку клиенту или переработаешь сверхурочно. Но когда речь заходит о получении денег, подарков, признания или помощи — ты неловко отмахиваешься («Да не стоит», «Мне и так нормально»). Ты подсознательно считаешь, что любовь и ресурсы нужно тяжело заслуживать.',
    rootBlock: 'Запрет на легкое принятие и чувство вины за изобилие',
    metrics: {
      desire: 85,
      action: 68,
      selfBelief: 58,
      receiving: 28,
    },
    firstShiftAdvice: 'Когда ты отказываешься принимать, ты перекрываешь циркуляцию изобилия. Научись говорить простое «Спасибо, я с радостью принимаю это» без встречных оправданий.',
    firstStepAction: 'Прими комплимент, помощь или оплату без скидки и без чувства неловкости.',
    recommendedHz: 528,
    recommendedProtocolId: 'proto-money',
    sevenDayJourneyTheme: 'Разрешение принимать ресурсы легко и с благодарностью',
    shareableQuote: '«Done with overgiving. I am now in my receiving era.»',
  },
  THE_BUILDER: {
    id: 'THE_BUILDER',
    nameRu: 'УПОРНЫЙ СТРОИТЕЛЬ',
    nameEn: 'THE BUILDER',
    eraTitle: 'Hustle Era → Leverage Era',
    tagline: '«Ты умеешь пахать и терпеть, но забываешь поднимать планку масштаба»',
    psychologicalMirror: 
      'Твоя дисциплина и выносливость вызывают уважение. Ты привык все тащить на себе, работать по 12 часов и решать проблемы силой воли. Но внутри ты чувствуешь потолок: сил уходит все больше, а финансовый и качественный скачок не происходит. Ты застрял в парадигме «чем тяжелее труд, тем больше результат», хотя реальный масштаб строится на рычагах и точности решений.',
    rootBlock: 'Привычка к сверхусилиям и недоверие делегированию',
    metrics: {
      desire: 95,
      action: 89,
      selfBelief: 72,
      receiving: 51,
    },
    firstShiftAdvice: 'Твой следующий уровень дохода и свободы лежит не в увеличении рабочих часов, а в смелости сказать «НЕТ» мелкой рутине ради одного крупного рычага.',
    firstStepAction: 'Делегируй, автоматизируй или просто удали одну мелкую задачу, которая съедает 2 часа в день.',
    recommendedHz: 888,
    recommendedProtocolId: 'proto-scale',
    sevenDayJourneyTheme: 'Переход от изнурительного труда к рычагам и масштабу',
    shareableQuote: '«From grind to grace. Upgrading my frequency to effortless scale.»',
  },
  THE_EXPANDER: {
    id: 'THE_EXPANDER',
    nameRu: 'РАСШИРЯЮЩИЙСЯ',
    nameEn: 'THE EXPANDER',
    eraTitle: 'Transition Era → Quantum Jump',
    tagline: '«Ты стоишь на пороге крупного масштаба — осталось сбросить старую идентичность»',
    psychologicalMirror: 
      'Ты уже прошел базовые уроки, зарабатываешь неплохие деньги и понимаешь законы фокуса. Но сейчас перед тобой маячит совсем другой порядок цифр, отношений и влияния. Старые методы больше не работают, а новая идентичность требует смелости отпустить привычный комфорт и признать свой истинный статус.',
    rootBlock: 'Страх перед собственной силой и ответственностью за масштаб',
    metrics: {
      desire: 96,
      action: 78,
      selfBelief: 81,
      receiving: 69,
    },
    firstShiftAdvice: 'Ты готов. Хватит играть в скромность. Начни вести переговоры и принимать решения из состояния человека, который уже находится в своей точке B.',
    firstStepAction: 'Озвучь условия или заключи сделку на новом, непривычно высоком для тебя уровне.',
    recommendedHz: 963,
    recommendedProtocolId: 'proto-scale',
    sevenDayJourneyTheme: 'Квантовый скачок в новую идентичность мастера',
    shareableQuote: '«I am entering my expander era. Big moves only.»',
  },
  THE_MAGNET: {
    id: 'THE_MAGNET',
    nameRu: 'МАГНИТ ВОЗМОЖНОСТЕЙ',
    nameEn: 'THE MAGNET',
    eraTitle: 'Aligned Era → Sovereign 5D',
    tagline: '«Состояние чистого присутствия, где желаемое материализуется естественно»',
    psychologicalMirror: 
      'Ты чувствуешь тонкую связь между своим внутренним состоянием и событиями вокруг. Когда ты спокоен, уверен и расслаблен — нужные звонки, идеи и деньги приходят без суеты. Твоя главная задача сейчас — удерживать эту чистоту вибрации и не скатываться в чужие паники и микро-драмы.',
    rootBlock: 'Потеря заземления и уязвимость к чужому низкочастотному шуму',
    metrics: {
      desire: 98,
      action: 84,
      selfBelief: 90,
      receiving: 88,
    },
    firstShiftAdvice: 'Оберегай свое утреннее состояние как самое дорогое сокровище. Твое спокойствие — это главный мультипликатор результатов.',
    firstStepAction: 'Проведи утренний ритуал в тишине и сделай главный стратегический шаг дня до первого захода в соцсети.',
    recommendedHz: 963,
    recommendedProtocolId: 'proto-quantum',
    sevenDayJourneyTheme: 'Абсолютный суверенитет и мастерство намерения',
    shareableQuote: '«In my magnetic era. Attracting, creating, thriving.»',
  },
};

export const QUIZ_QUESTIONS = [
  {
    id: 'q1',
    category: 'desire',
    question: 'Что сейчас сильнее всего отзывается в твоей душе?',
    subtitle: 'Выбери честно то, чего тебе действительно не хватает прямо сейчас',
    options: [
      {
        id: 'opt1_1',
        label: 'Деньги & Финансовая свобода',
        sub: 'Хочу перестать беспокоиться о счетах и позволить себе всё лучшее',
        archetypeWeight: { THE_SEEKER: 3, THE_BUILDER: 4, THE_BLOCKED_CREATOR: 2 },
      },
      {
        id: 'opt1_2',
        label: 'Любовь, глубина & Близость',
        sub: 'Хочу настоящую связь, романтику и чувство, что меня по-настоящему ценят',
        archetypeWeight: { THE_RECEIVER: 4, THE_BLOCKED_CREATOR: 2, THE_MAGNET: 2 },
      },
      {
        id: 'opt1_3',
        label: 'Уверенность & Проявление',
        sub: 'Хочу говорить смело, не бояться мнения людей и занять свое место',
        archetypeWeight: { THE_BLOCKED_CREATOR: 4, THE_SEEKER: 3, THE_RECEIVER: 2 },
      },
      {
        id: 'opt1_4',
        label: 'Новый этап: начать с чистого листа',
        sub: 'Чувствую, что старая жизнь исчерпала себя, хочу квантовый перезапуск',
        archetypeWeight: { THE_EXPANDER: 4, THE_MAGNET: 3, THE_SEEKER: 3 },
      },
    ],
  },
  {
    id: 'q2',
    category: 'block',
    question: 'Что чаще всего происходит, когда ты хочешь сделать важный шаг?',
    subtitle: 'Вспомни свое типичное внутреннее состояние в этот момент',
    options: [
      {
        id: 'opt2_1',
        label: 'Включается перфекционизм и сомнения: «Я еще не готов»',
        sub: 'Начинаю еще учиться, переделывать и откладывать момент релиза',
        archetypeWeight: { THE_SEEKER: 4, THE_BLOCKED_CREATOR: 3 },
      },
      {
        id: 'opt2_2',
        label: 'Появляется страх: «А вдруг откажут или осудят?»',
        sub: 'Горло сжимается, выбираю промолчать или сделать скидку',
        archetypeWeight: { THE_BLOCKED_CREATOR: 4, THE_RECEIVER: 3 },
      },
      {
        id: 'opt2_3',
        label: 'Начинаю пахать еще больше, но упираюсь в потолок сил',
        sub: 'Делаю всё сам, устаю, а квантового прорыва в деньгах нет',
        archetypeWeight: { THE_BUILDER: 4, THE_EXPANDER: 2 },
      },
      {
        id: 'opt2_4',
        label: 'Чувствую вину или неловкость, когда жизнь становится слишком легкой',
        sub: 'Привык, что всё должно доставаться через борьбу и преодоление',
        archetypeWeight: { THE_RECEIVER: 4, THE_BUILDER: 3 },
      },
    ],
  },
  {
    id: 'q3',
    category: 'money_relation',
    question: 'Как ты внутренне относишься к большим деньгам и изобилию?',
    subtitle: 'Честный маркер твоего текущего денежного термостата',
    options: [
      {
        id: 'opt3_1',
        label: 'Деньги быстро утекают, трудно удержать и приумножить',
        sub: 'Постоянное ощущение, что нужно экономить и контролировать каждую трату',
        archetypeWeight: { THE_SEEKER: 3, THE_RECEIVER: 3 },
      },
      {
        id: 'opt3_2',
        label: 'Мне неловко называть высокие чеки за свои услуги',
        sub: 'Кажется, что клиент уйдет, если я не сделаю скидку',
        archetypeWeight: { THE_RECEIVER: 4, THE_BLOCKED_CREATOR: 4 },
      },
      {
        id: 'opt3_3',
        label: 'Зарабатываю нормально, но устал быть рабом своей занятости',
        sub: 'Хочу масштаб, пассивный поток и свободу перемещений',
        archetypeWeight: { THE_BUILDER: 4, THE_EXPANDER: 3 },
      },
      {
        id: 'opt3_4',
        label: 'Готов выйти на миллионные обороты и новый уровень влияния',
        sub: 'Чувствую энергию для большого скачка, нужен четкий фокус',
        archetypeWeight: { THE_EXPANDER: 4, THE_MAGNET: 4 },
      },
    ],
  },
  {
    id: 'q4',
    category: 'body_state',
    question: 'Как твое тело чувствует себя большую часть дня?',
    subtitle: 'Тело никогда не врет — это зеркало твоего вибрационного состояния',
    options: [
      {
        id: 'opt4_1',
        label: 'Фоновая тревога, суета в голове, расфокус',
        sub: 'Слишком много информации, трудно усидеть на одной задаче',
        archetypeWeight: { THE_SEEKER: 4, THE_BLOCKED_CREATOR: 3 },
      },
      {
        id: 'opt4_2',
        label: 'Зажимы в шее, плечах и груди, поверхностное дыхание',
        sub: 'Ощущение груза ответственности и подавленных эмоций',
        archetypeWeight: { THE_RECEIVER: 4, THE_BUILDER: 3 },
      },
      {
        id: 'opt4_3',
        label: 'Усталость к середине дня, нехватка дофамина и драйва',
        sub: 'Нужно кофе или скроллинг, чтобы хоть как-то взбодриться',
        archetypeWeight: { THE_SEEKER: 3, THE_BUILDER: 3 },
      },
      {
        id: 'opt4_4',
        label: 'Периодами мощный поток, но не хватает стабильности',
        sub: 'Хочу уметь включать лазерное состояние в любой момент по щелчку',
        archetypeWeight: { THE_EXPANDER: 4, THE_MAGNET: 4 },
      },
    ],
  },
  {
    id: 'q5',
    category: 'ready_commitment',
    question: 'Если бы ты мог гарантированно изменить 1 вещь за 7 дней, что бы это было?',
    subtitle: 'Твой ключевой фокус для персональной программы 5D',
    options: [
      {
        id: 'opt5_1',
        label: 'Перестать бояться и сделать ключевой финансовый рывок',
        sub: 'Закрыть крупную сделку, повысить чек, запустить проект',
        archetypeWeight: { THE_BLOCKED_CREATOR: 4, THE_EXPANDER: 4 },
      },
      {
        id: 'opt5_2',
        label: 'Обрести железное спокойствие и внутренний стержень',
        sub: 'Перестать зависеть от мнения людей и чужого настроения',
        archetypeWeight: { THE_SEEKER: 4, THE_RECEIVER: 3 },
      },
      {
        id: 'opt5_3',
        label: 'Научиться легко притягивать возможности и людей',
        sub: 'Войти в состояние магнетизма и синхроничности',
        archetypeWeight: { THE_MAGNET: 4, THE_RECEIVER: 4 },
      },
      {
        id: 'opt5_4',
        label: 'Полная перезагрузка: стать новой версией себя',
        sub: 'Сбросить старый сценарий жизни и запустить эпоху изобилия',
        archetypeWeight: { THE_EXPANDER: 4, THE_MAGNET: 4, THE_SEEKER: 3 },
      },
    ],
  },
];

export const SEVEN_DAY_JOURNEYS: Record<string, SevenDayStep[]> = {
  DEFAULT: [
    {
      day: 1,
      theme: 'RECEIVE // Принятие',
      title: 'Снятие внутреннего сопротивления',
      subtitle: 'Разрешить себе принимать деньги, внимание и шансы без чувства вины',
      protocolId: 'proto-money',
      actionTitle: 'Прими комплимент или помощь без оправданий',
      actionDescription: 'Скажи искреннее «Благодарю» без попытки немедленно отдать долг.',
      isUnlocked: true,
    },
    {
      day: 2,
      theme: 'RELEASE // Очищение',
      title: 'Сброс старого сценария дефицита',
      subtitle: 'Очистить ментальный кэш и убрать микро-страхи бедности',
      protocolId: 'proto-reset',
      actionTitle: 'Выброси или отдай 3 вещи, напоминающие о нехватке',
      actionDescription: 'Освободи физическое пространство для входящего потока.',
      isUnlocked: false,
    },
    {
      day: 3,
      theme: 'ASK // Проявление',
      title: 'Смелость заявить о своей ценности',
      subtitle: 'Прямой голос, уверенный взгляд и отказ от демпинга',
      protocolId: 'proto-highagency',
      actionTitle: 'Озвучь свои условия или желаемую сумму прямо',
      actionDescription: 'Без извиняющихся смайликов и заискивающих формулировок.',
      isUnlocked: false,
    },
    {
      day: 4,
      theme: 'CREATE // Созидание',
      title: 'Лазерный фокус в чистом потоке',
      subtitle: '90 минут непрерывного созидания без проверки соцсетей',
      protocolId: 'proto-deepwork',
      actionTitle: 'Сделай 1 законченный релиз за один спринт',
      actionDescription: 'Выпусти прототип в свет вместо бесконечной полировки.',
      isUnlocked: false,
    },
    {
      day: 5,
      theme: 'ACT // Некомфортный шаг',
      title: 'Преодоление границы комфорта',
      subtitle: 'Действие, которое пугает, но дает максимальный финансовый рывок',
      protocolId: 'proto-decision',
      actionTitle: 'Сделай 1 контакт с человеком выше тебя по уровню',
      actionDescription: 'Предложи сотрудничество или ценность напрямую.',
      isUnlocked: false,
    },
    {
      day: 6,
      theme: 'EXPAND // Масштаб',
      title: 'Взгляд из изобилия и больших цифр',
      subtitle: 'Переход от выживания к мышлению рычагами и мультипликаторами',
      protocolId: 'proto-scale',
      actionTitle: 'Откажись от 1 мелкого клиента ради крупного',
      actionDescription: 'Освободи место под высокий средний чек.',
      isUnlocked: false,
    },
    {
      day: 7,
      theme: 'MANIFEST // Новая идентичность',
      title: 'Закрепление эпохи изобилия',
      subtitle: 'Полная интеграция нового вибрационного паттерна в материю',
      protocolId: 'proto-quantum',
      actionTitle: 'Отпразднуй новый статус и зафиксируй факт победы',
      actionDescription: 'Сделай красивый жест изобилия для себя.',
      isUnlocked: false,
    },
  ],
};

// Pricing experimentation sets — см. src/config/pricing.ts (PRICING_EXPERIMENTS).

export const ABUNDANCE_PILLARS: AbundancePillar[] = [
  {
    id: 'money',
    title: 'Деньги & Высокие чеки',
    subtitle: 'Снятие потолка и легкое принятие ресурсов',
    iconName: 'Coins',
    mindsetShift: {
      scarcity: '«Деньги достаются только тяжелым изнурительным трудом, их всегда мало».',
      abundance: '«Деньги — это нейтральная энергия обмена ценностью. Я легко принимаю оплату».',
    },
    practiceProtocolId: 'proto-money',
    realWorldAction: 'Озвучь ставку или чек на 30% выше привычного без оправданий.',
    reflectionPrompt: 'Что я чувствую в теле, когда мне переводят крупную сумму денег?',
    keyMantra: 'Я открыт свободному потоку ресурсов.',
  },
  {
    id: 'opportunity',
    title: 'Поток возможностей & Синхроничность',
    subtitle: 'Видеть скрытые двери и нужные контакты',
    iconName: 'Sparkles',
    mindsetShift: {
      scarcity: '«Всё уже занято, хороших клиентов и проектов не осталось».',
      abundance: '«Мир полон возможностей, которые ждут только моей готовности действовать».',
    },
    practiceProtocolId: 'proto-opportunity',
    realWorldAction: 'Напиши 1 человеку или компании с предложением взаимовыгодного сотрудничества.',
    reflectionPrompt: 'Какую возможность прямо перед моими глазами я игнорирую из-за страха?',
    keyMantra: 'Шансы находят меня везде, где я проявляюсь.',
  },
  {
    id: 'creation',
    title: 'Чистое созидание & Релизы',
    subtitle: 'Выход из бесконечной подготовки в готовый продукт',
    iconName: 'Zap',
    mindsetShift: {
      scarcity: '«Я еще недостаточно знаю, проект еще не идеален».',
      abundance: '«Сделанное лучше идеального. Ценность рождается в контакте с реальностью».',
    },
    practiceProtocolId: 'proto-deepwork',
    realWorldAction: 'Опубликуй или отправь готовый черновик прямо сегодня.',
    reflectionPrompt: 'Какой проект лежит у меня "в столе" больше месяца?',
    keyMantra: 'Я создаю и отпускаю в мир с легкостью.',
  },
  {
    id: 'courage',
    title: 'Смелость & Твердые границы',
    subtitle: 'Уверенный голос и отказ от заискивания',
    iconName: 'Flame',
    mindsetShift: {
      scarcity: '«Нужно всем нравиться и уступать, иначе меня отвергнут».',
      abundance: '«Мои границы вызывают уважение. Я выбираю тех, кто ценит мой уровень».',
    },
    practiceProtocolId: 'proto-highagency',
    realWorldAction: 'Скажи твердое «НЕТ» одной невыгодной просьбе или компромиссу.',
    reflectionPrompt: 'Где я предаю свои интересы ради чужого одобрения?',
    keyMantra: 'Моя сила в спокойной твердости.',
  },
  {
    id: 'receiving',
    title: 'Принятие признания & Комплиментов',
    subtitle: 'Разрешить себе быть видимым и оцененным',
    iconName: 'Heart',
    mindsetShift: {
      scarcity: '«Да не стоит, я ничего особенного не сделал».',
      abundance: '«Благодарю, я с радостью и достоинством принимаю признание».',
    },
    practiceProtocolId: 'proto-love',
    realWorldAction: 'Прими похвалу или подарок искренним «Спасибо» без обесценивания.',
    reflectionPrompt: 'Почему мне иногда стыдно радоваться своим победам?',
    keyMantra: 'Я достоин изобилия по праву рождения.',
  },
  {
    id: 'scale',
    title: 'Масштаб & Рычаги',
    subtitle: 'Переход от ручного труда к мультипликаторам',
    iconName: 'Layers',
    mindsetShift: {
      scarcity: '«Если хочешь сделать хорошо — сделай сам».',
      abundance: '«Масштаб строится на системах, делегировании и доверии команде».',
    },
    practiceProtocolId: 'proto-scale',
    realWorldAction: 'Делегируй или автоматизируй 1 повторяющийся процесс.',
    reflectionPrompt: 'Какое действие может принести результат в 10 раз больше за то же время?',
    keyMantra: 'Я мыслю рычагами и масштабом.',
  },
  {
    id: 'identity',
    title: 'Идентичность мастера 5D',
    subtitle: 'Действие из точки Б прямо сейчас',
    iconName: 'Crown',
    mindsetShift: {
      scarcity: '«Когда я заработаю X, тогда я стану уверенным».',
      abundance: '«Я уже действую из состояния достатка и силы. Результат следует за состоянием».',
    },
    practiceProtocolId: 'proto-quantum',
    realWorldAction: 'Прими одно важное решение так, как его принял бы ты через 3 года.',
    reflectionPrompt: 'Как изменится моя осанка и речь, когда я полностью присвою свой успех?',
    keyMantra: 'Я есть творец своей реальности.',
  },
];

export const REALITY_ENGINE_NODES: RealityEngineNode[] = [
  {
    id: 'thought',
    order: 1,
    title: '1. Внимание & Мысль',
    description: 'Куда направлено твое внимание в первые 60 минут после пробуждения?',
    practicalLever: 'Запрет на соцсети и новости до завершения утреннего ритуала.',
    auditQuestion: 'Чем я сейчас кормлю свой мозг: страхом нехватки или видением созидания?',
  },
  {
    id: 'state',
    order: 2,
    title: '2. Психофизическое состояние',
    description: 'Телесные зажимы, дыхание и частота сердечного ритма.',
    practicalLever: '3-минутная калибровка через частоты Solfeggio и глубокий выдох.',
    auditQuestion: 'Мое тело сейчас зажато в защите или расслаблено в уверенности?',
  },
  {
    id: 'decision',
    order: 3,
    title: '3. Выбор & Решение',
    description: 'Момент отказа от компромиссов и согласия на свой истинный уровень.',
    practicalLever: 'Фильтр: «Это решение из страха потерять или из смелости вырасти?»',
    auditQuestion: 'Какое решение я откладываю дольше всего?',
  },
  {
    id: 'action',
    order: 4,
    title: '4. Действие в материи',
    description: 'Конкретный некомфортный шаг в физическом мире.',
    practicalLever: 'Правило 5 минут: сделать звонок или релиз до включения внутреннего критика.',
    auditQuestion: 'Что я могу сделать прямо сейчас за 120 секунд?',
  },
  {
    id: 'result',
    order: 5,
    title: '5. Материальный факт',
    description: 'Заработанные деньги, заключенные договоры, завершенные продукты.',
    practicalLever: 'Фиксация в Reality Log с оценкой уровня дискомфорта.',
    auditQuestion: 'Какой факт подтверждает, что я сдвинулся с места?',
  },
  {
    id: 'identity',
    order: 6,
    title: '6. Закрепление идентичности',
    description: 'Новый базовый уровень нормы, из которого невозможно упасть обратно.',
    practicalLever: 'Празднование побед и присвоение нового статуса мастера.',
    auditQuestion: 'Кто я теперь, когда преодолел этот рубеж?',
  },
];

export const PRODUCT_CONFIG = {
  app: {
    name: '5DMAXING',
    tagline: 'Пятое измерение сознания & Эпоха Изобилия',
    subTagline: 'Переключи свое состояние за 3 минуты — и открой поток денег, любви и возможностей',
  },
  abundancePillars: ABUNDANCE_PILLARS,
  realityEngineNodes: REALITY_ENGINE_NODES,
  levels: [
    {
      level: 1,
      title: '3D Survival // Поиск выхода',
      subtitle: 'Суета, сомнения и ожидание идеального момента',
      identityStatement: '«Я признаю, что застрял в старых паттернах, и выбираю изменить всё».',
      requiredExp: 0,
      perks: ['Базовые протоколы', 'Дневник сдвигов'],
    },
    {
      level: 2,
      title: 'Awakening // Первые сдвиги',
      subtitle: 'Появление смелости и первый некомфортный шаг',
      identityStatement: '«Я перестаю уменьшать себя и начинаю открыто заявлять о желаниях».',
      requiredExp: 300,
      perks: ['Протоколы смелости', 'AI-Оракул'],
    },
    {
      level: 3,
      title: 'Abundance Magnet // Поток ресурсов',
      subtitle: 'Высокие чеки, снятие зажимов и легкое принятие',
      identityStatement: '«Изобилие — это мое естественное состояние. Деньги приходят на ценность».',
      requiredExp: 800,
      perks: ['Система Изобилия', 'Денежные протоколы'],
    },
    {
      level: 4,
      title: 'Sovereign Master // Чистое присутствие',
      subtitle: 'Абсолютный суверенитет, магнетизм и квантовый масштаб',
      identityStatement: '«Я создаю свою реальность из спокойствия и ясного намерения».',
      requiredExp: 2000,
      perks: ['Все 5D-инструменты', 'Закрытые протоколы'],
    },
  ],
};
